import { NextApiRequest, NextApiResponse } from 'next';
import multer, { MulterError } from 'multer';
import { NextRequest, NextResponse } from 'next/server';
import path from 'path';
const createMulterInstance = () => {
  return multer({
    storage: multer.diskStorage({
      destination: './public/assets/images',
      filename: (req, file, cb) => {
        const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
        const extension = path.extname(file.originalname);
        cb(null, uniqueSuffix + extension);
      },
    }),
  });
};

export async function POST(req: any, res: any) {
  try {
    // Create a multer instance
    const upload = createMulterInstance();
    const formData = await req.formData();

    // Extract form fields from formData
    const bname = formData.get('bname') as string;
    const url = formData.get('url') as string;
    const image = formData.get('image') as File;

    if (!image) {
      return NextResponse.json({ error: 'No file uploaded' });
    }

    // Use the multer middleware to handle file upload
    upload.single('image')(req, res, (err: any) => {
      if (err) {
        console.error('Error uploading file:', err);
        return NextResponse.json({ error: 'Internal server error' });
      } else {
        // File upload successful
        console.log(image)
        return NextResponse.json({ message: 'File uploaded successfully' });
        // const file = req.file; // Access the uploaded file info from req.file
        // if (!file) {
        //   return NextResponse.json({ error: 'No file uploaded' });
        // } else {
        //   return NextResponse.json({ message: 'File uploaded successfully', filename: file.filename });
        // }
      }
      
    });
    return NextResponse.json({ message: 'File uploaded successfully' });
    //   // File is uploaded successfully
    //   const file = req.file;
    //   if (!file) {
    //     return NextResponse.json({ error: 'No file uploaded' });
    //   }

    //   // Extract the filename generated by multer
    //   const filename = file.filename;

    //   // Send the extracted filename in the response
    //   res.setHeader('Content-Type', 'multipart/form-data');
    //   res.json({ filename });
    // });
  }  catch (err) {
    console.error('Unexpected error:', err);
    return NextResponse.json({ error: 'Unexpected error occurred' });
  }
}
